name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Repository
        run: echo ${{github.repository}}

      - name: Install dependencies
        run:   | 
          cd ${GITHUB_WORKSPACE}/vite-vue-project && npm install
          cd ${GITHUB_WORKSPACE}/vite-vue-project && npm run postinstall
          cd ${GITHUB_WORKSPACE}/vite-vue-project && npm run build
          cd ${GITHUB_WORKSPACE}/vite-vue-project && npm run generate
      - name: Change to gh pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          cd ${GITHUB_WORKSPACE}/vite-react-project && npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{github.repository}}

